module.exports = {
  purge: ["./pages/**/*.tsx", "./src/**/*.tsx"],
  darkMode: false, // or 'media' or 'class'
  safelist: [
    "bg-pink-50",
    "bg-amber-50",
    "bg-green-50",
    "bg-cyan-50",
    "bg-indigo-50",
    "bg-violet-50",
    "bg-purple-50",
    "bg-sky-50",
    "bg-fuchsia-50",
    "bg-rose-50",
    "text-pink-400",
    "text-rose-400",
    "text-amber-400",
    "text-green-400",
    "text-cyan-400",
    "text-indigo-400",
    "text-violet-400",
    "text-purple-400",
    "text-sky-400",
    "text-fuchsia-400",
    "text-red-400",
    "text-red-400",
    "border-rose-400",
    "border-pink-400",
    "border-amber-400",
    "border-green-400",
    "border-cyan-400",
    "border-indigo-400",
    "border-violet-400",
    "border-purple-400",
    "border-sky-400",
    "border-fuchsia-400",
    "border-red-400",
    "border-red-400",
  ],
  theme: {
    extend: {
      screens: {
        betterhover: { raw: "(hover: hover)" },
      },
      fontFamily: {
        Constructio: ["ConstructioGrotesk-Regular"],
        Courier: ["courier-std"],
        CourierBold: ["Courier-Bold"],
        Abril: ["Abril Fatface"],
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
