export { Main } from "./main";
export { Github } from "./github";
export { AboutMe } from "./aboutMe";
export { Experience } from "./experience"
export { Skills } from './skills'
export { SkillsMobile } from './skills/index.mobile'
export { Contact } from './contact'
export { ContactMobile } from './contact/index.mobile'
export { Projects } from './projects'
